apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer # Expone el frontend/backend al exterior a través de un balanceador de carga
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
  selector:
    app: web
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
spec:
  type: NodePort # Permite acceder a la interfaz de n8n
  ports:
    - port: 5688
      targetPort: 5678
      protocol: TCP
  selector:
    app: n8n
---
apiVersion: v1
kind: Service
metadata:
  name: mailer
spec:
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: http
      port: 8025
      targetPort: 8025
  selector:
    app: mailer
